language: c
compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - libpcap-dev

script: cd $TEST_DIR && make

env:
  - TEST_DIR=fingerprintls

sudo: false

notifications:
  slack: squarelemon:Reg7U43QgRTUIB8CBpWYcv2O
